version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - node -v
      - npm -v

  pre_build:
    commands:
      - npm ci

  build:
    commands:
      - npm run build
      - pwd
      - ls -al
      - ls -al build || true
      - ls -al dist || true

artifacts:
  base-directory: dist
  files:
    - '**/*'
