# buildspec.yml
version: 0.2

phases:
  pre_build: 
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      - pwd
      - ls -al
      - ls -al build || true
      - ls -al dist || true

artifacts: 
  files:
    - '**/*'
  base-directory: dist
